# Generated by Django 5.0.4 on 2024-04-13 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palavras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra_portugues', models.TextField()),
                ('palavra_pronuncia', models.CharField(max_length=255)),
                ('palavra_ingles', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.ManyToManyField(related_name='frases', to='ingles_portugues.palavras')),
            ],
        ),
        migrations.CreateModel(
            name='Palavras_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra_portugues', models.TextField()),
                ('palavra_pronuncia', models.CharField(max_length=255)),
                ('palavra_ingles', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palavras_usuario', to='ingles_portugues.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Frases_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase_ingles', models.TextField()),
                ('frase_traduziada', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frases_usuario', to='ingles_portugues.usuario')),
            ],
        ),
    ]
